### ISSUE TITLE
Stack exhausted on feather s2

### ISSUE THREAD

**Issue by richardanaya** [adafruit/Adafruit_CircuitPython_JWT#13]
https://gist.github.com/richardanaya/2158b09c52c3b2ea904aaeb48c524062

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 9, in <module>
  File "/lib/adafruit_jwt.py", line 101, in generate
RuntimeError: pystack exhausted
```

**Comment by richardanaya** [comment]
I misunderstood the parameters
